kind: pipeline
name: default
steps:
  - name: build
    image: damianoneill/golang-alpine-builder
    volumes:
      - name: go
        path: /go
    commands:
      - export GOPROXY=https://goproxy.io
      - export GO111MODULE=on
      - go version
      - go env
#      - go mod vendor
      - echo "拉取依赖, ok"
      - go build -ldflags "-w -s" -o main main.go
      - echo "项目编译, ok"
      - ./main test

    when:
      event:
        - tag

  - name: publish
    image: plugins/docker
    restore: true
    settings:
      repo: registry.cn-shanghai.aliyuncs.com/ybase/${DRONE_REPO_NAME}
      registry: registry.cn-shanghai.aliyuncs.com
      tags: ${DRONE_TAG:latest}
      username:
        from_secret: username
      password:
        from_secret: password
    when:
      status:
        - success
      event:
        - tag

  - name: deploy_dev
    image: pterosaurs/drone-kube
    settings:
      template: ./deploy/deployment_dev.yml
      server: https://192.168.1.100:6443
      token:
        from_secret: token_beta
    when:
      ref:
        include:
          - refs/tags/*.dev
      status:
        - success
      event:
        - tag

  - name: deploy_stag
    image: pterosaurs/drone-kube
    settings:
      template: ./deploy/deployment_stag.yml
      server: https://47.102.143.100:5443
      token:
        from_secret: token_beta
    when:
      ref:
        include:
          - refs/tags/*.stag
      status:
        - success
      event:
        - tag

  - name: deploy_release
    image: pterosaurs/drone-kube
    settings:
      template: ./deploy/deployment_prod.yml
      server: https://192.168.1.66:6443
      token:
        from_secret: token_release
    when:
      ref:
        exclude:
          - refs/tags/*.dev
          - refs/tags/*.stag
        include:
          - refs/tags/*.prod
      status:
        - success
      event:
        - tag

  - name: wechat_success_prod
    image: clem109/drone-wechat
    settings:
      corpid:
        from_secret: corpid
      corp_secret:
        from_secret: corp_secret
      agent_id:
        from_secret: agent_id
      title: ${DRONE_REPO_NAME}
      description: "Build Tag: ${DRONE_TAG:latest} success. ${DRONE_COMMIT_AUTHOR}."
      msg_url: ${DRONE_BUILD_LINK}
      btn_txt: btn
    when:
      event:
        - tag
      ref:
        include:
          - refs/tags/*.prod
      status: [ success ]

  - name: wechat_failed_prod
    image: clem109/drone-wechat
    settings:
      corpid:
        from_secret: corpid
      corp_secret:
        from_secret: corp_secret
      agent_id:
        from_secret: agent_id
      title: ${DRONE_REPO_NAME}
      description: "Build Tag: ${DRONE_TAG:latest} failed. ${DRONE_COMMIT_AUTHOR} please fix. Check the results here: ${DRONE_BUILD_LINK} "
      msg_url: ${DRONE_BUILD_LINK}
      btn_txt: btn
    when:
      event:
        - tag
      ref:
        include:
          - refs/tags/*.prod
      status: [ failure ]

  - name: wechat_success_stag
    image: clem109/drone-wechat
    settings:
      corpid:
        from_secret: corpid
      corp_secret:
        from_secret: staging_corp_secret
      agent_id:
        from_secret: staging_agent_id
      title: ${DRONE_REPO_NAME}
      description: "Build Tag: ${DRONE_TAG:latest} success. ${DRONE_COMMIT_AUTHOR}."
      msg_url: ${DRONE_BUILD_LINK}
      btn_txt: btn
    when:
      event:
        - tag
      ref:
        include:
          - refs/tags/*.stag

      status: [ success ]

  - name: wechat_failed_stag
    image: clem109/drone-wechat
    settings:
      corpid:
        from_secret: corpid
      corp_secret:
        from_secret: staging_corp_secret
      agent_id:
        from_secret: staging_agent_id
      title: ${DRONE_REPO_NAME}
      description: "Build Tag: ${DRONE_TAG:latest} failed. ${DRONE_COMMIT_AUTHOR} please fix. Check the results here: ${DRONE_BUILD_LINK} "
      msg_url: ${DRONE_BUILD_LINK}
      btn_txt: btn
    when:
      event:
        - tag
      ref:
        include:
          - refs/tags/*.stag
      status: [ failure ]

  - name: wechat_success_dev
    image: clem109/drone-wechat
    settings:
      corpid:
        from_secret: corpid
      corp_secret:
        from_secret: test_corp_secret
      agent_id:
        from_secret: test_agent_id
      title: ${DRONE_REPO_NAME}
      description: "Build Tag: ${DRONE_TAG:latest} success. ${DRONE_COMMIT_AUTHOR}."
      msg_url: ${DRONE_BUILD_LINK}
      btn_txt: btn
      when:
        event:
          - tag
        ref:
          include:
            - refs/tags/*.dev
        status: [ success ]

  - name: wechat_failed_dev
    image: clem109/drone-wechat
    settings:
      corpid:
        from_secret: corpid
      corp_secret:
        from_secret: test_corp_secret
      agent_id:
        from_secret: test_agent_id
      title: ${DRONE_REPO_NAME}
      description: "Build Tag: ${DRONE_TAG:latest} failed. ${DRONE_COMMIT_AUTHOR} please fix. Check the results here: ${DRONE_BUILD_LINK} "
      msg_url: ${DRONE_BUILD_LINK}
      btn_txt: btn
    when:
      event:
        - tag
      ref:
        include:
          - refs/tags/*.dev
      status: [ failure ]

volumes:
  - name: go
    host:
      path: /go
---
kind: secret
name: username
get:
  path: drone-secret
  name: username
---
kind: secret
name: password
get:
  path: drone-secret
  name: password
---
kind: secret
name: token_beta
get:
  path: drone-secret
  name: token_beta
---
kind: secret
name: token_release
get:
  path: drone-secret
  name: token_release
---
kind: secret
name: agent_id
get:
  path: drone-secret
  name: agent_id
---
kind: secret
name: corp_secret
get:
  path: drone-secret
  name: corp_secret
---
kind: secret
name: corpid
get:
  path: drone-secret
  name: corpid
---
kind: secret
name: test_agent_id
get:
  path: test-drone-secret
  name: agent_id
---
kind: secret
name: test_corp_secret
get:
  path: test-drone-secret
  name: corp_secret
---
kind: secret
name: staging_agent_id
get:
  path: staging-drone-secret
  name: agent_id
---
kind: secret
name: staging_corp_secret
get:
  path: staging-drone-secret
  name: corp_secret