kind: pipeline
name: default
steps:
- name: publish
  image: plugins/docker
  restore: true
  settings:
    repo: registry.cn-shanghai.aliyuncs.com/ybase/${DRONE_REPO_NAME}
    registry: registry.cn-shanghai.aliyuncs.com
    tags: ${DRONE_TAG:latest}
    username:
      from_secret: username
    password:
      from_secret: password
- name: deployment_test
  image: pterosaurs/drone-kube
  settings:
    template: ./deploy/deployment_test.yml
    server: https://192.168.1.100:6443
    token:
      from_secret: token_beta
  when:
    status:
    - success
    ref:
    - refs/tags/*.test
- name: test_wechat_success
  image: clem109/drone-wechat
  settings:
    corpid:
      from_secret: corpid
    corp_secret:
      from_secret: test_corp_secret
    agent_id:
      from_secret: test_agent_id
    title: ${DRONE_REPO_NAME}
    description: "Build Tag: ${DRONE_TAG:latest} success. ${DRONE_COMMIT_AUTHOR}."
    msg_url: ${DRONE_BUILD_LINK}
    btn_txt: btn
  when:
    ref:
    - refs/tags/*.test
    status: [ success ]
- name: test_wechat_failed
  image: clem109/drone-wechat
  settings:
    corpid:
      from_secret: corpid
    corp_secret:
      from_secret: test_corp_secret
    agent_id:
      from_secret: test_agent_id
    title: ${DRONE_REPO_NAME}
    description: "Build Tag: ${DRONE_TAG:latest} failed. ${DRONE_COMMIT_AUTHOR} please fix. Check the results here: ${DRONE_BUILD_LINK} "
    msg_url: ${DRONE_BUILD_LINK}
    btn_txt: btn
  when:
    ref:
    - refs/tags/*.test
    status: [ failure ]
- name: staging_wechat_success
  image: clem109/drone-wechat
  settings:
    corpid:
      from_secret: corpid
    corp_secret:
      from_secret: staging_corp_secret
    agent_id:
      from_secret: staging_agent_id
    title: ${DRONE_REPO_NAME}
    description: "Build Tag: ${DRONE_TAG:latest} success. ${DRONE_COMMIT_AUTHOR}."
    msg_url: ${DRONE_BUILD_LINK}
    btn_txt: btn
  when:
    ref:
    - refs/tags/*.staging
    status: [ success ]
- name: staging_wechat_failed
  image: clem109/drone-wechat
  settings:
    corpid:
      from_secret: corpid
    corp_secret:
      from_secret: staging_corp_secret
    agent_id:
      from_secret: staging_agent_id
    title: ${DRONE_REPO_NAME}
    description: "Build Tag: ${DRONE_TAG:latest} failed. ${DRONE_COMMIT_AUTHOR} please fix. Check the results here: ${DRONE_BUILD_LINK} "
    msg_url: ${DRONE_BUILD_LINK}
    btn_txt: btn
  when:
    ref:
    - refs/tags/*.staging
    status: [ failure ]
- name: release_wechat_success
  image: clem109/drone-wechat
  settings:
    corpid:
      from_secret: corpid
    corp_secret:
      from_secret: corp_secret
    agent_id:
      from_secret: agent_id
    title: ${DRONE_REPO_NAME}
    description: "Build Tag: ${DRONE_TAG:latest} success. ${DRONE_COMMIT_AUTHOR}."
    msg_url: ${DRONE_BUILD_LINK}
    btn_txt: btn
  when:
    ref:
    - refs/tags/*.release
    status: [ success ]
- name: release_wechat_failed
  image: clem109/drone-wechat
  settings:
    corpid:
      from_secret: corpid
    corp_secret:
      from_secret: corp_secret
    agent_id:
      from_secret: agent_id
    title: ${DRONE_REPO_NAME}
    description: "Build Tag: ${DRONE_TAG:latest} failed. ${DRONE_COMMIT_AUTHOR} please fix. Check the results here: ${DRONE_BUILD_LINK} "
    msg_url: ${DRONE_BUILD_LINK}
    btn_txt: btn
  when:
    ref:
    - refs/tags/*.release
    status: [ failure ]
trigger:
  event:
  - tag
---
kind: secret
name: username
get:
  path: drone-secret
  name: username
---
kind: secret
name: password
get:
  path: drone-secret
  name: password
---
kind: secret
name: token_beta
get:
  path: drone-secret
  name: token_beta
---
kind: secret
name: token_release
get:
  path: drone-secret
  name: token_release
---
kind: secret
name: agent_id
get:
  path: drone-secret
  name: agent_id
---
kind: secret
name: corp_secret
get:
  path: drone-secret
  name: corp_secret
---
kind: secret
name: corpid
get:
  path: drone-secret
  name: corpid
---
kind: secret
name: test_agent_id
get:
  path: test-drone-secret
  name: agent_id
---
kind: secret
name: test_corp_secret
get:
  path: test-drone-secret
  name: corp_secret
---
kind: secret
name: staging_agent_id
get:
  path: staging-drone-secret
  name: agent_id
---
kind: secret
name: staging_corp_secret
get:
  path: staging-drone-secret
  name: corp_secret