kind: pipeline
type: docker
name: build

clone:
    depth: 1

steps:
    -   name: publish
        image: plugins/docker
        settings:
            repo: registry-vpc.cn-shanghai.aliyuncs.com/ybase/${DRONE_REPO_NAME}
            registry: registry-vpc.cn-shanghai.aliyuncs.com
            tags: ${DRONE_TAG:latest}
            username:
                from_secret: username
            password:
                from_secret: password
        when:
            ref:
                include:
                    - refs/tags/*release
                    - refs/tags/*staging
trigger:
    event:
        - tag
---
kind: pipeline
type: docker
name: deploy-release

clone:
    disable: true

steps:
    -   name: clone
        image: alpine/git
        commands:
            - git clone --depth=1 https://git.dev.yuanben.org/scm/helm/{REPLACE}.git .
    
    -   name: tag
        image: python
        commands:
            - pip install -r requirements.txt
            - python revision.py {REPLACE}=${DRONE_TAG:latest}
    
    -   name: deploy
        image: pelotech/drone-helm3
        settings:
            mode: upgrade
            chart: ./
            release: { REPLACE }
            kube_api_server: https://192.168.1.136:6443
            kube_token:
                from_secret: token_release1
            skip_tls_verify: true
    
    -   name: push commit
        image: appleboy/drone-git-push
        settings:
            remote: ssh://git@git.dev.yuanben.org:7999/helm/{REPLACE}.git
            remote_name: deploy
            commit: true
            commit_message: drone deploy {REPLACE}=${DRONE_TAG:latest}
            author_name: drone
            author_email: drone@yuanben.org
            ssh_key:
                from_secret: helm_git_key
trigger:
    ref:
        - refs/tags/*release
depends_on:
    - build
---
kind: pipeline
type: docker
name: deploy-staging

clone:
    disable: true

steps:
    -   name: clone
        image: alpine/git
        commands:
            - git clone -b staging --depth=1 https://git.dev.yuanben.org/scm/helm/{REPLACE}.git .
    
    -   name: tag
        image: python
        commands:
            - pip install -r requirements.txt
            - python revision.py {REPLACE}=${DRONE_TAG:latest}
    
    -   name: deploy
        image: pelotech/drone-helm3
        settings:
            mode: upgrade
            chart: ./
            release: {REPLACE}
            kube_api_server: https://192.168.1.115:6443
            kube_token:
                from_secret: token_beta
            skip_tls_verify: true
    
    -   name: push commit
        image: appleboy/drone-git-push
        settings:
            remote: ssh://git@git.dev.yuanben.org:7999/helm/{REPLACE}.git
            branch: staging
            remote_name: deploy
            commit: true
            commit_message: drone deploy {REPLACE}=${DRONE_TAG:latest}
            author_name: drone
            author_email: drone@yuanben.org
            ssh_key:
                from_secret: helm_git_key
trigger:
    ref:
        - refs/tags/*staging
depends_on:
    - build
---
kind: secret
name: token_beta
get:
    path: drone-secret
    name: token_beta
---
kind: secret
name: username
get:
    path: drone-secret
    name: username
---
kind: secret
name: password
get:
    path: drone-secret
    name: password
---
kind: secret
name: helm_git_key
get:
    path: drone-secret
    name: helm_git_key
---
kind: secret
name: token_release1
get:
    path: drone-secret
    name: token_release1