version: '3'
services:
    api:
        image: go-service:dev
        container_name: go-service-api
        depends_on:
            - migrate
        ports:
            - 8080:8080
        environment:
            WORK: server
            ENV: config
        volumes:
            - ./config:/app/config
    migrate:
        image: go-service:dev
        container_name: go-service-migrate
        environment:
            WORK: migrate
            ENV: config
        volumes:
            - ./config:/app/config

        