version: '3'
services:
    api:
        build: .
        image: ${IMAGE}:${VERSION}
        container_name: ${NAME}-api
        depends_on:
            - migrate
        ports:
            - 8080:8080
        environment:
            WORK: server
            ENV: config
        volumes:
            - ./config:/app/config
    migrate:
        image: ${IMAGE}:${VERSION}
        container_name: ${NAME}-migrate
        environment:
            WORK: migrate
            ENV: config
        volumes:
            - ./config:/app/config

        