apiVersion: v1
kind: Pod
metadata:
  name: {app_name}-migration
spec:
  selector:
    matchLabels:
      app: {app_name}-migration
  replicas: 0
  containers:
  - name: {app_name}-migration
    image: registry-vpc.cn-shanghai.aliyuncs.com/ybase/{app_name}:{{build.tag}}
    args: ["migrate"]
    resources:
      requests:
        memory: "300Mi"
        cpu: 300m
      limits:
        memory: "1000Mi"
        cpu: 1000m
    volumeMounts:
    - name: app-config
      mountPath: /app/config

  imagePullPolicy: Always
  restartPolicy: Never
  imagePullSecrets:
  - name: shanghai-aliyunsecret

  volumes:
  - name: app-config
    configMap:
      name: {app_name}-config