apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portal
  namespace: turing
spec:
  selector:
    matchLabels:
      app:  portal
  replicas: 1
  template:
    metadata:
      labels:
        app: portal
        build: "{{build.number}}"
    spec:
      containers:
      - name: portal
        image: registry.cn-shanghai.aliyuncs.com/ybase/{{repo.name}}:latest
        env:
          - name: env
            value: "stag"
        resources:
          requests:
            memory: "300Mi"
            cpu: 300m
          limits:
            memory: "1000Mi"
            cpu: 1000m

      imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: shanghai-aliyunsecret