apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-service
  namespace: turing
spec:
  selector:
    matchLabels:
      app:  go-service
  replicas: 1
  template:
    metadata:
      labels:
        app: go-service
        build: "{{build.number}}"
    spec:
      containers:
      - name: go-service
        image: registry.cn-shanghai.aliyuncs.com/ybase/{{repo.name}}:latest
        env:
          - name: env
            value: "stag"
        resources:
          requests:
            memory: "300Mi"
            cpu: 300m
          limits:
            memory: "1000Mi"
            cpu: 1000m
        volumeMounts:
          - name: config-volume
            mountPath: /app/config

      imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: shanghai-aliyunsecret
      volumes:
        - name: config-volume
          configMap:
            name: {{repo.name}}-config
