apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{repo.name}}
spec:
  selector:
    matchLabels:
      app: {{repo.name}}
  replicas: 0
  template:
    metadata:
      labels:
        app: {{repo.name}}
    spec:
      containers:
        - name: {{repo.name}}
          image: registry-vpc.cn-shanghai.aliyuncs.com/ybase/{{repo.name}}:{{build.tag}}
          args: ["server"]
          resources:
            requests:
              memory: "300Mi"
              cpu: 300m
            limits:
              memory: "1000Mi"
              cpu: 1000m
      imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: shanghai-aliyunsecret
