apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{repo.name}}
  namespace: {{namespace}}
spec:
  selector:
    matchLabels:
      app:  {{repo.name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{repo.name}}
        build: "{{build.number}}"
    spec:
      containers:
        - name: {{repo.name}}
          image: registry.cn-shanghai.aliyuncs.com/ybase/{{repo.name}}:latest
          resources:
            requests:
              memory: "300Mi"
              cpu: 300m
            limits:
              memory: "1000Mi"
              cpu: 1000m

      imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: shanghai-aliyunsecret