db:
  driver: "mysql"
  connection: "root:mypass@(192.168.1.100:30036)/turing"
log:
  app_id: "test.env.config.0111"
  format: "%L %e %D %T %a %f %S %M"
  stdout: true
  level: "debug" # debug info notice warning error critical
  filter:
    - "A1"
    - "A2"
http:
  host: "0.0.0.0"
  port: "8081"
