environment: "debug"
db:
    driver: "mysql"
    connection: "root:mypass@(host.docker.internal:3306)/go_service"
log:
    level: "debug"
    ginMode: "debug"
http:
    host: "0.0.0.0"
    port: "8080"
allow_origins:
    - https://go.service