environment: "debug"
db:
    driver: "mysql"
    connection: "root:mypass@(host.docker.internal:3306)/go_service"
log:
    level: "debug"
    ginMode: "debug"
http:
    host: "0.0.0.0"
    port: "8080"
allow_origins:
    - https://go.service
oss:
    endpoint: "oss-cn-shanghai.aliyuncs.com"
    access_key_id: "xxxxxxxxxxxxxxxxxxxxx"
    access_key_secret: "xxxxxxxxxxxxxxxxxxxxx"
    bucket: proof-staging
    path_prefix: "files/"
    callback_url: "https://ip.yuanben.site"
file:
    storage_type: 1
    storage_url: "https://file.hndip.cn"
session:
    driver: "memory"
    secret_key: "secret_key"
    connection: ""
    login_max_age_seconds: 36000
    vault_max_age_seconds: 3600