name: build docker image dev
on:
    push:
        branches:
            - master
        tags-ignore:
            - v*
        paths-ignore:
            - '.github/**'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                
            -   name: Login to DockerHub
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            
            -   name: Docker build and push
                uses: docker/build-push-action@v2
                with:
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
